filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - decode_json_fields:
          fields: ["log"]
          target: "json"
          overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "finance-log-%{+yyyy.MM}"

setup.template.name: "finance-log"
setup.template.pattern: "finance-log-*"
setup.ilm.enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/data/log
  name: filebeat
